services:
  # Budget buddy Telegram bot
  finance-app:
    build:
      context: ./finance_bot
    container_name: personal_finance_bot
    restart: always
    environment:
      - TOKEN=${TOKEN} # Your bot token
      - ALLOWED_ID=${ALLOWED_ID} # Your telegram ID
    volumes:
      - ./data:/app/data
